
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import {  
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: "backend testing for fire detection",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider   fallbackRedirectUrl="/dashboard"
    appearance={{
      baseTheme : dark
    }}>
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
      <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem
    >
    <Header />
<main className="min-h-screen">
{children}
</main>  
<Toaster richColors/>
<footer className="bg-muted/50 py-12">
<div className="container mx-auto px-4 text-center text-gray-200 ">
<p>Made by Aman ❤️😎</p>
</div> 
</footer>
</ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
